export const PROJECTS_DATA = [
    {
        "id":143,
        "date":"2021-08-13T00:04:39",
        "date_gmt":"2021-08-13T00:04:39",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=143"
        },
        "modified":"2021-08-14T22:30:08",
        "modified_gmt":"2021-08-14T22:30:08",
        "slug":"98-desert-mountain",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/98-desert-mountain\/",
        "title":{
            "rendered":"98 Desert Mountain"
        },
        "template":"",
        "acf":{
            "name":"98 Desert Mountain",
            "location":"Scottsdale, AZ",
            "size":"",
            "year":"2008",
            "status":"",
            "services":" Architecture and interior design",
            "main_image":{
                "ID":15,
                "id":15,
                "title":"hor-artboard_3",
                "filename":"hor-artboard_3.png",
                "filesize":1581807,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3.png",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/test-proyect-1\/hor-artboard_3\/",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"hor-artboard_3",
                "status":"inherit",
                "uploaded_to":14,
                "date":"2020-11-19 03:38:05",
                "modified":"2020-11-19 03:38:05",
                "menu_order":0,
                "mime_type":"image\/png",
                "type":"image",
                "subtype":"png",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":1150,
                "height":768,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-150x150.png",
                    "thumbnail-width":150,
                    "thumbnail-height":150,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-300x200.png",
                    "medium-width":300,
                    "medium-height":200,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-768x513.png",
                    "medium_large-width":768,
                    "medium_large-height":513,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-1024x684.png",
                    "large-width":1024,
                    "large-height":684,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3.png",
                    "1536x1536-width":1150,
                    "1536x1536-height":768,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3.png",
                    "2048x2048-width":1150,
                    "2048x2048-height":768,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-830x554.png",
                    "sydney-large-thumb-width":830,
                    "sydney-large-thumb-height":554,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-550x400.png",
                    "sydney-medium-thumb-width":550,
                    "sydney-medium-thumb-height":400,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-230x154.png",
                    "sydney-small-thumb-width":230,
                    "sydney-small-thumb-height":154,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-350x234.png",
                    "sydney-service-thumb-width":350,
                    "sydney-service-thumb-height":234,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/hor-artboard_3-480x321.png",
                    "sydney-mas-thumb-width":480,
                    "sydney-mas-thumb-height":321
                }
            },
            "home_page_order":"8"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/98-great-room-night-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/98-Entry-court-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/143K5916-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/143K5958-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/143K6609-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/143K6616-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/great-room-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/143K5909-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9368-min.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/143"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=143"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    },
    {
        "id":45,
        "date":"2021-08-02T21:34:48",
        "date_gmt":"2021-08-02T21:34:48",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=45"
        },
        "modified":"2021-08-14T00:47:34",
        "modified_gmt":"2021-08-14T00:47:34",
        "slug":"2570-park",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/2570-park\/",
        "title":{
            "rendered":"2570 Park"
        },
        "template":"",
        "acf":{
            "name":"2570 Park",
            "location":" Laguna Beach, CA",
            "size":"",
            "year":"2020",
            "status":"",
            "services":"Architecture",
            "main_image":{
                "ID":58,
                "id":58,
                "title":"2570park-main",
                "filename":"2570park-main.jpg",
                "filesize":1683788,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/2570-park\/2570park-main\/",
                "alt":"",
                "author":"3",
                "description":"",
                "caption":"",
                "name":"2570park-main",
                "status":"inherit",
                "uploaded_to":45,
                "date":"2021-08-04 16:58:33",
                "modified":"2021-08-04 16:58:33",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":0,
                "height":0,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "thumbnail-width":1,
                    "thumbnail-height":1,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "medium-width":1,
                    "medium-height":1,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "medium_large-width":1,
                    "medium_large-height":1,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "large-width":1,
                    "large-height":1,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "1536x1536-width":1,
                    "1536x1536-height":1,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "2048x2048-width":1,
                    "2048x2048-height":1,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "sydney-large-thumb-width":1,
                    "sydney-large-thumb-height":1,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "sydney-medium-thumb-width":1,
                    "sydney-medium-thumb-height":1,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "sydney-small-thumb-width":1,
                    "sydney-small-thumb-height":1,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "sydney-service-thumb-width":1,
                    "sydney-service-thumb-height":1,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/2570park-main.jpg",
                    "sydney-mas-thumb-width":1,
                    "sydney-mas-thumb-height":1
                }
            },
            "home_page_order":"1"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-2.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-1.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-8.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-7.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-6.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-5.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-4.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/257-park-3.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/45"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=45"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    },
    {
        "id":44,
        "date":"2021-08-02T21:34:11",
        "date_gmt":"2021-08-02T21:34:11",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=44"
        },
        "modified":"2021-08-14T22:14:12",
        "modified_gmt":"2021-08-14T22:14:12",
        "slug":"1091-skyline-dr",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/1091-skyline-dr\/",
        "title":{
            "rendered":"1091 Skyline Dr"
        },
        "template":"",
        "acf":{
            "name":"1091 Skyline Dr",
            "location":"Laguna Beach, CA",
            "size":"",
            "year":"2014",
            "status":"",
            "services":"Architecture and interior design",
            "main_image":{
                "ID":100,
                "id":100,
                "title":"1091skyline-main",
                "filename":"1091skyline-main.jpg",
                "filesize":262105,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main.jpg",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/1091-skyline-dr\/1091skyline-main\/",
                "alt":"",
                "author":"3",
                "description":"",
                "caption":"",
                "name":"1091skyline-main",
                "status":"inherit",
                "uploaded_to":44,
                "date":"2021-08-06 16:08:15",
                "modified":"2021-08-06 16:08:15",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":1200,
                "height":800,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-150x150.jpg",
                    "thumbnail-width":150,
                    "thumbnail-height":150,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-300x200.jpg",
                    "medium-width":300,
                    "medium-height":200,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-768x512.jpg",
                    "medium_large-width":768,
                    "medium_large-height":512,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-1024x683.jpg",
                    "large-width":1024,
                    "large-height":683,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main.jpg",
                    "1536x1536-width":1200,
                    "1536x1536-height":800,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main.jpg",
                    "2048x2048-width":1200,
                    "2048x2048-height":800,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-830x553.jpg",
                    "sydney-large-thumb-width":830,
                    "sydney-large-thumb-height":553,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-550x400.jpg",
                    "sydney-medium-thumb-width":550,
                    "sydney-medium-thumb-height":400,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-230x153.jpg",
                    "sydney-small-thumb-width":230,
                    "sydney-small-thumb-height":153,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-350x233.jpg",
                    "sydney-service-thumb-width":350,
                    "sydney-service-thumb-height":233,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-main-480x320.jpg",
                    "sydney-mas-thumb-width":480,
                    "sydney-mas-thumb-height":320
                }
            },
            "home_page_order":"2"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-1.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-2.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-3.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-4.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/1091skyline-5.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/44"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=44"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    },
    {
        "id":43,
        "date":"2021-08-02T21:33:14",
        "date_gmt":"2021-08-02T21:33:14",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=43"
        },
        "modified":"2021-08-14T22:14:48",
        "modified_gmt":"2021-08-14T22:14:48",
        "slug":"740-barracuda",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/740-barracuda\/",
        "title":{
            "rendered":"740 Barracuda"
        },
        "template":"",
        "acf":{
            "name":"740 Barracuda",
            "location":"Laguna Beach, CA",
            "size":"",
            "year":"2013",
            "status":"",
            "services":"Architecture",
            "main_image":{
                "ID":124,
                "id":124,
                "title":"Lopez Residence-9118 (1)-min",
                "filename":"Lopez-Residence-9118-1-min-scaled.jpg",
                "filesize":248185,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-scaled.jpg",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/740-barracuda\/lopez-residence-9118-1-min\/",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"lopez-residence-9118-1-min",
                "status":"inherit",
                "uploaded_to":43,
                "date":"2021-08-12 11:49:20",
                "modified":"2021-08-12 11:58:40",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":2560,
                "height":1707,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-150x150.jpg",
                    "thumbnail-width":150,
                    "thumbnail-height":150,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-300x200.jpg",
                    "medium-width":300,
                    "medium-height":200,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-768x512.jpg",
                    "medium_large-width":768,
                    "medium_large-height":512,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-1024x683.jpg",
                    "large-width":1024,
                    "large-height":683,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-1536x1024.jpg",
                    "1536x1536-width":1536,
                    "1536x1536-height":1024,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-scaled.jpg",
                    "2048x2048-width":2048,
                    "2048x2048-height":1366,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-scaled.jpg",
                    "sydney-large-thumb-width":830,
                    "sydney-large-thumb-height":553,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-scaled.jpg",
                    "sydney-medium-thumb-width":550,
                    "sydney-medium-thumb-height":367,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-scaled.jpg",
                    "sydney-small-thumb-width":230,
                    "sydney-small-thumb-height":153,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-scaled.jpg",
                    "sydney-service-thumb-width":350,
                    "sydney-service-thumb-height":233,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9118-1-min-scaled.jpg",
                    "sydney-mas-thumb-width":480,
                    "sydney-mas-thumb-height":320
                }
            },
            "home_page_order":"7"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9126-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9134-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9135-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9150-min.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/Lopez-Residence-9368-min.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/43"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=43"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    },
    {
        "id":42,
        "date":"2021-08-02T21:32:32",
        "date_gmt":"2021-08-02T21:32:32",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=42"
        },
        "modified":"2021-08-14T22:15:03",
        "modified_gmt":"2021-08-14T22:15:03",
        "slug":"721-manzanita",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/721-manzanita\/",
        "title":{
            "rendered":"721 Manzanita"
        },
        "template":"",
        "acf":{
            "name":"721 Manzanita",
            "location":"Laguna Beach, CA",
            "size":"",
            "year":"2016",
            "status":"",
            "services":"Architecture and Interior Design",
            "main_image":{
                "ID":86,
                "id":86,
                "title":"721manzanita-main",
                "filename":"721manzanita-main.jpg",
                "filesize":115671,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main.jpg",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/721-manzanita\/721manzanita-main\/",
                "alt":"",
                "author":"3",
                "description":"",
                "caption":"",
                "name":"721manzanita-main",
                "status":"inherit",
                "uploaded_to":42,
                "date":"2021-08-06 15:57:08",
                "modified":"2021-08-06 15:57:08",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":945,
                "height":625,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-150x150.jpg",
                    "thumbnail-width":150,
                    "thumbnail-height":150,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-300x198.jpg",
                    "medium-width":300,
                    "medium-height":198,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-768x508.jpg",
                    "medium_large-width":768,
                    "medium_large-height":508,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main.jpg",
                    "large-width":945,
                    "large-height":625,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main.jpg",
                    "1536x1536-width":945,
                    "1536x1536-height":625,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main.jpg",
                    "2048x2048-width":945,
                    "2048x2048-height":625,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-830x549.jpg",
                    "sydney-large-thumb-width":830,
                    "sydney-large-thumb-height":549,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-550x400.jpg",
                    "sydney-medium-thumb-width":550,
                    "sydney-medium-thumb-height":400,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-230x152.jpg",
                    "sydney-small-thumb-width":230,
                    "sydney-small-thumb-height":152,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-350x231.jpg",
                    "sydney-service-thumb-width":350,
                    "sydney-service-thumb-height":231,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-main-480x317.jpg",
                    "sydney-mas-thumb-width":480,
                    "sydney-mas-thumb-height":317
                }
            },
            "home_page_order":"3"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-1.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-2.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-3.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-4.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-5.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-6.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2021\/08\/721manzanita-7.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/42"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=42"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    },
    {
        "id":28,
        "date":"2020-12-08T23:05:10",
        "date_gmt":"2020-12-08T23:05:10",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=28"
        },
        "modified":"2021-08-14T22:15:24",
        "modified_gmt":"2021-08-14T22:15:24",
        "slug":"test-3",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/test-3\/",
        "title":{
            "rendered":"405 Dartmoor"
        },
        "template":"",
        "acf":{
            "name":"405 Dartmoor",
            "location":"Laguna Beach, CA",
            "size":"",
            "year":"2017",
            "status":"",
            "services":"Architecture",
            "main_image":{
                "ID":78,
                "id":78,
                "title":"405dartmoor-main",
                "filename":"405dartmoor-main.jpg",
                "filesize":340793,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main.jpg",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/test-3\/405dartmoor-main\/",
                "alt":"",
                "author":"3",
                "description":"",
                "caption":"",
                "name":"405dartmoor-main",
                "status":"inherit",
                "uploaded_to":28,
                "date":"2021-08-06 15:48:59",
                "modified":"2021-08-06 15:48:59",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":1062,
                "height":960,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-150x150.jpg",
                    "thumbnail-width":150,
                    "thumbnail-height":150,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-300x271.jpg",
                    "medium-width":300,
                    "medium-height":271,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-768x694.jpg",
                    "medium_large-width":768,
                    "medium_large-height":694,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-1024x926.jpg",
                    "large-width":1024,
                    "large-height":926,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main.jpg",
                    "1536x1536-width":1062,
                    "1536x1536-height":960,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main.jpg",
                    "2048x2048-width":1062,
                    "2048x2048-height":960,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-830x750.jpg",
                    "sydney-large-thumb-width":830,
                    "sydney-large-thumb-height":750,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-550x400.jpg",
                    "sydney-medium-thumb-width":550,
                    "sydney-medium-thumb-height":400,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-230x208.jpg",
                    "sydney-small-thumb-width":230,
                    "sydney-small-thumb-height":208,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-350x316.jpg",
                    "sydney-service-thumb-width":350,
                    "sydney-service-thumb-height":316,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-main-480x434.jpg",
                    "sydney-mas-thumb-width":480,
                    "sydney-mas-thumb-height":434
                }
            },
            "home_page_order":"4"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-1.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-2.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-3.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-4.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-4.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-5.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-6.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/12\/405dartmoor-7.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/28"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=28"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    },
    {
        "id":19,
        "date":"2020-11-23T20:07:01",
        "date_gmt":"2020-11-23T20:07:01",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=19"
        },
        "modified":"2021-08-14T22:15:39",
        "modified_gmt":"2021-08-14T22:15:39",
        "slug":"test-project-2",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/test-project-2\/",
        "title":{
            "rendered":"395 Dartmoor"
        },
        "template":"",
        "acf":{
            "name":"395 Dartmoor",
            "location":"Laguna Beach, CA",
            "size":"",
            "year":"2015",
            "status":"",
            "services":"Architecture",
            "main_image":{
                "ID":72,
                "id":72,
                "title":"395dartmoor-main",
                "filename":"395dartmoor-main-scaled.jpg",
                "filesize":436969,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-scaled.jpg",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/test-project-2\/395dartmoor-main\/",
                "alt":"",
                "author":"3",
                "description":"",
                "caption":"",
                "name":"395dartmoor-main",
                "status":"inherit",
                "uploaded_to":19,
                "date":"2021-08-06 15:42:38",
                "modified":"2021-08-06 15:42:38",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":2560,
                "height":1920,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-150x150.jpg",
                    "thumbnail-width":150,
                    "thumbnail-height":150,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-300x225.jpg",
                    "medium-width":300,
                    "medium-height":225,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-768x576.jpg",
                    "medium_large-width":768,
                    "medium_large-height":576,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-1024x768.jpg",
                    "large-width":1024,
                    "large-height":768,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-1536x1152.jpg",
                    "1536x1536-width":1536,
                    "1536x1536-height":1152,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-scaled.jpg",
                    "2048x2048-width":2048,
                    "2048x2048-height":1536,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-scaled.jpg",
                    "sydney-large-thumb-width":830,
                    "sydney-large-thumb-height":623,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-scaled.jpg",
                    "sydney-medium-thumb-width":533,
                    "sydney-medium-thumb-height":400,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-scaled.jpg",
                    "sydney-small-thumb-width":230,
                    "sydney-small-thumb-height":173,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-scaled.jpg",
                    "sydney-service-thumb-width":350,
                    "sydney-service-thumb-height":263,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-main-scaled.jpg",
                    "sydney-mas-thumb-width":480,
                    "sydney-mas-thumb-height":360
                }
            },
            "home_page_order":"5"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-1.png",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-2.png",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-3.png",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-4-scaled.jpg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/395dartmoor-5-scaled.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/19"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=19"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    },
    {
        "id":14,
        "date":"2020-11-19T03:39:18",
        "date_gmt":"2020-11-19T03:39:18",
        "guid":{
            "rendered":"https:\/\/wp.conradarchitect.com\/?post_type=projects&#038;p=14"
        },
        "modified":"2021-08-14T22:15:54",
        "modified_gmt":"2021-08-14T22:15:54",
        "slug":"test-proyect-1",
        "status":"publish",
        "type":"projects",
        "link":"https:\/\/wp.conradarchitect.com\/projects\/test-proyect-1\/",
        "title":{
            "rendered":"195 Monarch Bay"
        },
        "template":"",
        "acf":{
            "name":"195 Monarch Bay",
            "location":"Monarch Beach, CA",
            "size":"",
            "year":"2019",
            "status":"",
            "services":"Architecture",
            "main_image":{
                "ID":46,
                "id":46,
                "title":"DSC08385_1-min",
                "filename":"DSC08385_1-min-scaled.jpg",
                "filesize":1323521,
                "url":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-scaled.jpg",
                "link":"https:\/\/wp.conradarchitect.com\/projects\/test-proyect-1\/dsc08385_1-min\/",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"dsc08385_1-min",
                "status":"inherit",
                "uploaded_to":14,
                "date":"2021-08-02 21:43:05",
                "modified":"2021-08-02 21:43:05",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/wp.conradarchitect.com\/wp-includes\/images\/media\/default.png",
                "width":2560,
                "height":1709,
                "sizes":{
                    "thumbnail":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-150x150.jpg",
                    "thumbnail-width":150,
                    "thumbnail-height":150,
                    "medium":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-300x200.jpg",
                    "medium-width":300,
                    "medium-height":200,
                    "medium_large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-768x513.jpg",
                    "medium_large-width":768,
                    "medium_large-height":513,
                    "large":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-1024x683.jpg",
                    "large-width":1024,
                    "large-height":683,
                    "1536x1536":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-1536x1025.jpg",
                    "1536x1536-width":1536,
                    "1536x1536-height":1025,
                    "2048x2048":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-scaled.jpg",
                    "2048x2048-width":2048,
                    "2048x2048-height":1367,
                    "sydney-large-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-scaled.jpg",
                    "sydney-large-thumb-width":830,
                    "sydney-large-thumb-height":554,
                    "sydney-medium-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-scaled.jpg",
                    "sydney-medium-thumb-width":550,
                    "sydney-medium-thumb-height":367,
                    "sydney-small-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-scaled.jpg",
                    "sydney-small-thumb-width":230,
                    "sydney-small-thumb-height":154,
                    "sydney-service-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-scaled.jpg",
                    "sydney-service-thumb-width":350,
                    "sydney-service-thumb-height":234,
                    "sydney-mas-thumb":"https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/DSC08385_1-min-scaled.jpg",
                    "sydney-mas-thumb-width":480,
                    "sydney-mas-thumb-height":320
                }
            },
            "home_page_order":"6"
        },
        "gallery_images":[
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch10-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch9-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch8-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch2-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch4-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch5-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch6-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch7-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch2-min-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/Monarch11-scaled.jpeg",
            "https:\/\/wp.conradarchitect.com\/wp-content\/uploads\/2020\/11\/195monarchbay-12-scaled.jpg"
        ],
        "_links":{
            "self":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects\/14"
                }
            ],
            "collection":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/projects"
                }
            ],
            "about":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/types\/projects"
                }
            ],
            "wp:attachment":[
                {
                    "href":"https:\/\/wp.conradarchitect.com\/wp-json\/wp\/v2\/media?parent=14"
                }
            ],
            "curies":[
                {
                    "name":"wp",
                    "href":"https:\/\/api.w.org\/{rel}",
                    "templated":true
                }
            ]
        }
    }
]
